### ISSUE TITLE
Project detail for Website.

### ISSUE THREAD

**Issue by praweensoni01** [andmhn/climate-awareness#9]
Give me Project heading and details so i can implement it.

**Comment by andmhn** [comment]
leave the header-bar as it is for now

we should discuss about the body content
________________________________
इससे: Praween Soni ***@***.***>
भेजे गए: 23 जुलाई 2024 17:41
प्रति: andmhn/climate-awareness ***@***.***>
प्रतिलिपि: Subscribed ***@***.***>
विषय: [andmhn/climate-awareness] Project detail for Website. (Issue #9)


Give me Project heading and details so i can implement it.

**Comment by andmhn** [comment]
project heading should be "Know Our Climate"
below this we would write some quotes with pictures

**Comment by andmhn** [comment]
it has to be done in body component

now we should do it in new branch
